import pandas as pd
from pathlib import Path
from typing import Optional
from utils.logger import setup_logger

logger = setup_logger("jtl_parser")

class JTLParser:
    def parse_jtl(self, jtl_path: Path) -> pd.DataFrame:
        """
        Parse JTL (XML) generated by JMeter into a pandas DataFrame.
        Ensure relevant fields: timeStamp, elapsed, label, threadName, success, responseData, samplerData, requestHeaders, responseHeaders
        """
        if not Path(jtl_path).exists():
            raise FileNotFoundError(f"JTL file not found: {jtl_path}")

        try:
            df = pd.read_xml(jtl_path)
        except Exception:
            logger.exception("Failed to read JTL as XML, trying fallback with xmltodict")
            import xmltodict
            with open(jtl_path, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            obj = xmltodict.parse(content)
            # Normalize into DataFrame - best effort
            samples = obj.get('testResults', {}).get('httpSample') or obj.get('testResults', {}).get('sample') or []
            df = pd.json_normalize(samples)

        # Ensure columns exist
        for col in ['timeStamp','elapsed','label','threadName','success','responseData','samplerData','requestHeaders','responseHeaders']:
            if col not in df.columns:
                df[col] = None

        logger.info("Parsed JTL, rows=%d", len(df))
        return df
